#!/usr/bin/env python3
"""Runbook scaffolder (Phase 14).

Scaffolds the surrounding assets for a new runbook or a new category:

  * ensures the category directory exists
  * generates/refreshes a category ``README.md`` index listing its runbooks
  * can scaffold Mermaid diagram stubs and an example-output file under
    ``examples/`` for a given runbook

Usage:
    python tools/runbook_generator/runbook_scaffolder.py --category databases
    python tools/runbook_generator/runbook_scaffolder.py --all-readmes
    python tools/runbook_generator/runbook_scaffolder.py --example postgresql-optimization
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from runbook_lib import (  # type: ignore  # noqa: E402
    REPO_ROOT,
    RUNBOOKS_DIR,
    bold,
    green,
    load_runbooks,
    yellow,
)

CATEGORY_BLURB = {
    "reliability": "Incident response, RCA, postmortems, and production/DR readiness.",
    "observability": "Metrics, logs, and traces reviews; SLI/SLO and alerting quality.",
    "databases": "Performance and health reviews for relational, in-memory, document, and vector stores.",
    "messaging": "Event streaming and event-driven architecture operations.",
    "security": "Defensive security audits across IaC, containers, APIs, identity, and AI systems.",
    "kubernetes": "Cluster and managed-service (EKS/AKS/GKE) audits.",
    "cloud-cost": "FinOps and cost optimization across AWS, Azure, and GCP.",
    "migrations": "Framework/language upgrades and architectural migrations.",
    "architecture": "Architecture and platform-engineering reviews.",
    "cicd": "CI/CD pipeline debugging and deployment failure analysis.",
    "ai-ml": "Operations for RAG, LLM inference, MCP, prompts, and agent evaluation.",
    "data": "Data pipeline reliability and data-quality operations.",
    "soc": "Security operations: triage, detection tuning, and threat hunting.",
}


def category_dir(cat: str) -> Path:
    return RUNBOOKS_DIR / cat


def write_category_readme(cat: str) -> bool:
    d = category_dir(cat)
    if not d.exists():
        d.mkdir(parents=True, exist_ok=True)
    runbooks = [rb for rb in load_runbooks() if rb.category == cat]
    lines = [
        f"# {cat.replace('-', ' ').title()} Runbooks",
        "",
        CATEGORY_BLURB.get(cat, "Operational runbooks for this domain."),
        "",
        f"**{len(runbooks)} runbook(s)** in this category.",
        "",
        "| Runbook | Difficulty | Risk | Maturity | Agents |",
        "|---------|-----------|------|----------|--------|",
    ]
    for rb in sorted(runbooks, key=lambda r: r.title):
        agents = len(rb.supported_agents)
        lines.append(
            f"| [{rb.title}](./{rb.path.name}) | {rb.meta.get('difficulty', '-')} | "
            f"{rb.meta.get('risk_level', '-')} | {rb.meta.get('maturity', '-')} | {agents} |"
        )
    lines += ["", "> Generated by `tools/runbook_generator/runbook_scaffolder.py`.", ""]
    (d / "README.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return True


def write_example_stub(runbook_id: str) -> bool:
    by_id = {rb.slug: rb for rb in load_runbooks()}
    rb = by_id.get(runbook_id)
    if not rb:
        print(yellow(f"Unknown runbook id: {runbook_id}"))
        return False
    out = REPO_ROOT / "examples" / f"{runbook_id}-example.md"
    if out.exists():
        print(yellow(f"{out.relative_to(REPO_ROOT)} already exists; leaving as-is."))
        return False
    content = f"""# Example — {rb.title}

> Fictional, illustrative example execution of
> [`{rb.rel}`](../{rb.rel}). All names and values are synthetic.

## Inputs

```text
service_name: <example>
environment: staging
```

## Agent plan (externalized)

```text
Objective: {rb.section_body('Objective').strip().splitlines()[0] if rb.section_body('Objective').strip() else '...'}
Steps (read-only first): 1) ... 2) ... 3) ...
```

## Deliverable — Standard Report (excerpt)

```markdown
# Agent Execution Report — {rb.title}

## Executive Summary
...

## Findings
1. F1 — ...

## Recommendations
| ID | Recommendation | Effort | Risk if ignored |
|----|----------------|--------|-----------------|
| R1 | ... | S | ... |
```
"""
    out.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--category", help="scaffold/refresh a category dir + README")
    parser.add_argument("--all-readmes", action="store_true", help="refresh all category READMEs")
    parser.add_argument("--example", help="scaffold an example file for a runbook id")
    args = parser.parse_args()

    did = False
    if args.category:
        write_category_readme(args.category)
        print(green(f"Scaffolded category: runbooks/{args.category}/ (README refreshed)"))
        did = True
    if args.all_readmes:
        cats = sorted({rb.category for rb in load_runbooks()})
        for cat in cats:
            write_category_readme(cat)
        print(green(bold(f"Refreshed README for {len(cats)} categories.")))
        did = True
    if args.example:
        if write_example_stub(args.example):
            print(green(f"Scaffolded example for {args.example}."))
        did = True

    if not did:
        parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
