#!/usr/bin/env python3
"""Repository analytics / observability engine (Phase 25).

Computes repository-wide metrics and writes ``metrics/repository-metrics.json``
plus a human-readable ``metrics/DASHBOARD.md`` snapshot. Metrics include totals,
category/domain/agent distributions, quality and maturity scores, review status,
and contributor stats (derived from git history when available).

Usage:
    python metrics/repository_metrics.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from collections import Counter
from datetime import date
from pathlib import Path

# Bootstrap shared lib from tools/.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))

from runbook_lib import (  # type: ignore  # noqa: E402
    REPO_ROOT,
    bold,
    green,
    load_runbooks,
    maturity_level_number,
    write_json,
)

MATURITY_NAMES = {1: "Draft", 2: "Validated", 3: "Production", 4: "Enterprise", 5: "Reference Standard"}


def git_contributors() -> int:
    try:
        out = subprocess.run(
            ["git", "shortlog", "-sne", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, timeout=20,
        )
        if out.returncode == 0:
            return len([ln for ln in out.stdout.splitlines() if ln.strip()])
    except Exception:
        pass
    return 0


def git_commit_count() -> int:
    try:
        out = subprocess.run(
            ["git", "rev-list", "--count", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, timeout=20,
        )
        if out.returncode == 0:
            return int(out.stdout.strip() or 0)
    except Exception:
        pass
    return 0


def load_quality_mean() -> float | None:
    p = REPO_ROOT / "quality" / "quality-score.json"
    if p.exists():
        return json.loads(p.read_text(encoding="utf-8")).get("mean_score")
    return None


def main() -> int:
    runbooks = load_runbooks()
    n = len(runbooks)

    categories = Counter(rb.category for rb in runbooks)
    domains = Counter(rb.meta.get("domain", rb.category) for rb in runbooks)
    difficulties = Counter(rb.meta.get("difficulty", "intermediate") for rb in runbooks)
    risk = Counter(rb.meta.get("risk_level", "unknown") for rb in runbooks)
    status = Counter(rb.meta.get("status", "approved") for rb in runbooks)
    hitl = Counter(rb.meta.get("human_in_the_loop", "unknown") for rb in runbooks)
    agents = Counter()
    for rb in runbooks:
        for a in rb.supported_agents:
            agents[a] += 1

    maturity_levels = Counter(maturity_level_number(rb.meta.get("maturity"), rb.meta.get("status")) for rb in runbooks)
    total_words = sum(rb.word_count() for rb in runbooks)
    total_diagrams = sum(rb.mermaid_count() for rb in runbooks)

    metrics = {
        "generated_by": "metrics/repository_metrics.py",
        "generated_on": date.today().isoformat(),
        "totals": {
            "runbooks": n,
            "categories": len(categories),
            "total_words": total_words,
            "avg_words": round(total_words / n) if n else 0,
            "total_mermaid_diagrams": total_diagrams,
            "contributors": git_contributors(),
            "commits": git_commit_count(),
        },
        "quality": {
            "mean_completeness_score": load_quality_mean(),
        },
        "distributions": {
            "by_category": dict(categories.most_common()),
            "by_domain": dict(domains.most_common()),
            "by_difficulty": dict(difficulties.most_common()),
            "by_risk_level": dict(risk.most_common()),
            "by_status": dict(status.most_common()),
            "by_human_in_the_loop": dict(hitl.most_common()),
            "by_agent_support": dict(agents.most_common()),
            "by_maturity_level": {MATURITY_NAMES[k]: v for k, v in sorted(maturity_levels.items())},
        },
    }
    write_json(REPO_ROOT / "metrics" / "repository-metrics.json", metrics)

    # Human-readable dashboard snapshot.
    lines = [
        "# Repository Metrics Dashboard",
        "",
        f"> Auto-generated by `metrics/repository_metrics.py` on {metrics['generated_on']}.",
        "",
        "## Totals",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Runbooks | {n} |",
        f"| Categories | {len(categories)} |",
        f"| Total words | {total_words:,} |",
        f"| Avg words / runbook | {metrics['totals']['avg_words']:,} |",
        f"| Mermaid diagrams | {total_diagrams} |",
        f"| Contributors | {metrics['totals']['contributors']} |",
        f"| Commits | {metrics['totals']['commits']} |",
        f"| Mean completeness score | {metrics['quality']['mean_completeness_score']} |",
        "",
        "## Runbooks by category",
        "",
        "| Category | Count |",
        "|----------|-------|",
    ]
    for cat, cnt in categories.most_common():
        lines.append(f"| {cat} | {cnt} |")
    lines += ["", "## Runbooks by maturity level", "", "| Level | Count |", "|-------|-------|"]
    for k in sorted(maturity_levels):
        lines.append(f"| L{k} — {MATURITY_NAMES[k]} | {maturity_levels[k]} |")
    lines += ["", "## Agent support coverage", "", "| Agent | Runbooks |", "|-------|----------|"]
    for a, cnt in agents.most_common():
        lines.append(f"| {a} | {cnt} |")
    lines.append("")
    (REPO_ROOT / "metrics" / "DASHBOARD.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")

    print(bold("Repository metrics"))
    print(f"  runbooks={n} categories={len(categories)} words={total_words:,} contributors={metrics['totals']['contributors']}")
    print(green("Wrote metrics/repository-metrics.json and metrics/DASHBOARD.md"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
